name: TDLight (Windows)
on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit, branch or tag to checkout'
        required: false
        default: ''

jobs:
  build:
    runs-on: windows-latest
    name: Build

    steps:
      - name: Install packages
        run: |
          vcpkg install gperf openssl:x86-windows zlib:x86-windows
      - name: Clone TDLight
        uses: actions/checkout@v2
        with: 
          repository: tdlight-team/tdlight
          ref: ${{ github.event.inputs.commit }}
      - name: Configure
        shell: cmd
        run: |
          mkdir build
          cd build
          call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars32.bat"
          cmake -A Win32 -DCMAKE_INSTALL_PREFIX:PATH=../tdlight -DCMAKE_TOOLCHAIN_FILE:FILEPATH=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ..
      - name: Build and install
        run: |
          cd build
          cmake --build . --target install --config Release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: TDLight
          path: tdlight
